version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_goldeneggs
    ports:
      - "6011:8080"

    depends_on:
      - db
    networks:
      - goldeneggs_net

  db:
    image: mysql:8.0
    container_name: mysql_goldeneggs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2210
      MYSQL_DATABASE: goldeneggs
    volumes:
      - ./Config/mysql:/var/lib/mysql
    hostname: goldeneggs_database
    networks:
      - goldeneggs_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p2210"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer_goldeneggs
    restart: always
    networks:
      - goldeneggs_net

  proxy:
    build:
      context: .   # la raíz de tu proyecto
      dockerfile: nginx/Dockerfile
    container_name: nginx_goldeneggs
    ports:
      - "6010:80"
    depends_on:
      - backend
    networks:
      - goldeneggs_net

networks:
  goldeneggs_net:
    driver: bridge
